language: cpp
compiler:
  - gcc
env:
  - OMP_NUM_THREADS=4 CXX=g++-4.8 FC=gfortran-4.8 OCCA_PTHREADS_ENABLED=1 OCCA_OPENMP_ENABLED=1 OCCA_OPENCL_ENABLED=1 OCCA_CUDA_ENABLED=0 OCCA_COI_ENABLED=0 OCCA_OCCA_FORTRAN_ENABLED=1
before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers gcc-4.8 g++-4.8 gfortran-4.8
script:
  - make
  - cd examples/addVectors && make
  - LD_LIBRARY_PATH=../../lib:$LD_LIBRARY_PATH ./main
# - LD_LIBRARY_PATH=../../lib:$LD_LIBRARY_PATH ./main_c
  - LD_LIBRARY_PATH=../../lib:$LD_LIBRARY_PATH ./main_f90
