language: cpp
compiler:
  - gcc
env:
  global:
    - OCCA_DIR=$TRAVIS_BUILD_DIR
    - OMP_NUM_THREADS=4
    - ASAN_OPTIONS=detect_leaks=1
    - FC=gfortran-4.9
    - OCCA_FORTRAN_ENABLED=1
    - LD_LIBRARY_PATH=$OCCA_DIR/lib:$LD_LIBRARY_PATH
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers gcc-4.9 g++-4.9 gfortran-4.9
  - export CXX=g++-4.9
  - export CC=gcc-4.9
script:
  - echo 'with library address sanitizer'
  - make -j CXXFLAGS='-fsanitize=address -fno-omit-frame-pointer -g' FCFLAGS='-fsanitize=address -fno-omit-frame-pointer -g'
  - cd $OCCA_DIR/examples/addVectors/
  - make -j CXXFLAGS='-fsanitize=address -fno-omit-frame-pointer -g' FCFLAGS='-fsanitize=address -fno-omit-frame-pointer -g'
  - ./main
  - ./main_c
  - ./main_f90
  - make clean
  - cd $OCCA_DIR/examples/reduction/
  - make -j CXXFLAGS='-fsanitize=address -fno-omit-frame-pointer -g' FCFLAGS='-fsanitize=address -fno-omit-frame-pointer -g'
  - ./main
  - make clean
  - cd $OCCA_DIR/examples/usingArrays/
  - make -j CXXFLAGS='-fsanitize=address -fno-omit-frame-pointer -g' FCFLAGS='-fsanitize=address -fno-omit-frame-pointer -g'
  - ./main
  - make clean
  - echo 'without library address sanitizer'
  - cd $OCCA_DIR
  - make clean
  - make -j CXXFLAGS='-fno-omit-frame-pointer -g' FCFLAGS='-fno-omit-frame-pointer -g'
  - cd $OCCA_DIR/examples/addVectors/
  - make -j CXXFLAGS='-fsanitize=address -fno-omit-frame-pointer -g' FCFLAGS='-fsanitize=address -fno-omit-frame-pointer -g'
  - ./main
  - ./main_c
  - ./main_f90
  - make clean
  - cd $OCCA_DIR/examples/reduction/
  - make -j CXXFLAGS='-fsanitize=address -fno-omit-frame-pointer -g' FCFLAGS='-fsanitize=address -fno-omit-frame-pointer -g'
  - ./main
  - make clean
  - cd $OCCA_DIR/examples/usingArrays/
  - make -j CXXFLAGS='-fsanitize=address -fno-omit-frame-pointer -g' FCFLAGS='-fsanitize=address -fno-omit-frame-pointer -g'
  - ./main
  - make clean

notifications:
  email:
    recipients:
      - dmed256@gmail.com
      - spam.warburton@gmail.com
    on_success: [never]
    on_failure: [always]
