language: cpp
compiler:
  - gcc
  - clang++
env:
  - OCCA_DIR=$TRAVIS_BUILD_DIR
  - OMP_NUM_THREADS=4
  - CXX=g++-4.8 FC=gfortran-4.8
  - OCCA_PTHREADS_ENABLED=1 OCCA_OPENMP_ENABLED=1 OCCA_OPENCL_ENABLED=1 OCCA_CUDA_ENABLED=0 OCCA_COI_ENABLED=0 OCCA_FORTRAN_ENABLED=1
  - LD_LIBRARY_PATH=$OCCA_DIR/lib:$LD_LIBRARY_PATH
before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers gcc-4.8 g++-4.8 gfortran-4.8
script:
  - make
  - cd $OCCA_DIR/examples/addVectors
  - make
  - ./main
  - ./main_c
  - ./main_f90
  - cd $OCCA_DIR/examples/reduction
  - make
  - ./main

notifications:
  email:
    recipients:
      - dmed256@gmail.com
      - spam.warburton@gmail.com
    on_success: [never]
    on_failure: [always]
